/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RectangleTest"
 * 	found in "/home/boliu/liubo/lte_rrc_asn/Rectangle.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Rectangle_H_
#define	_Rectangle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Rectangle */
typedef struct Rectangle {
	long	 height;
	long	 width;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Rectangle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Rectangle;

#ifdef __cplusplus
}
#endif

#endif	/* _Rectangle_H_ */
#include <asn_internal.h>
